server:
  port: 20001

spring:
  application:
    name: order-service

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/msa?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  output:
    ansi:
      enabled: always

  # zipkin:
  #   base-url: http://localhost:9411
  #   enabled: true

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.format_sql: false
    show-sql: true
    open-in-view: false

logging:
  level:
    org.springframework.web: DEBUG    # HTTP 요청 관련 로그 (Actuator HTTP 엔드포인트) 이거 해야 다 나옴...
  pattern:
    correlation: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0 # 모든 요청을 추적 (0.1로 설정하면 10%만 추적)
    zipkin:
      enabled: true
      endpoint: http://localhost:9411/api/v2/spans

first-service-url: http://localhost:40001
order-service-url: http://localhost:20001
catalog-service-url: http://localhost:20002

KafkaProdcerTopic: orders