# 이미지 node 16버전 
FROM node:18

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# port 열기로 선언..
# docker run -p 5173:5173
EXPOSE 5173

# 마지막 명령어는 npm run dev 실행해라...
CMD ["npm", "run", "dev"]